export const data= [{
    "id": 1,
    "name": "Transporter 3 ",
    "nombre": "Transporter 3 ",
    "genero": "Comedia",
    "clase": " 1",
    "sipnosis": "Con el fin de volver a juntar a su desequilibrada familia y fortalecer los lazos familiares, Rusty Griswold (Ed Helms) decide repetir el viaje de vacaciones familiares que hizo cuando era pequeño. Decide cruzar todo el país junto a su esposa Debbie (Christina Applegate) y sus dos hijos Jack (Skyler Gisondo) y Kevin (Steele Stebbins) para ir al parque de atracciones favorito de las familias, Walley World. Sin embargo, no todo va a salir como tenía planificado Rusty. El filme supone una nueva entrega de la saga National Lampoon´s Vacation. En esta ocasión está protagonizada por Ed Helms (R3sacón, Somos los Miller), Christina Applegate (Carta Blanca), Chris Hemsworth (Rush, Thor: El mundo oscuro) y Chevy Chase (la serie de televisión Community). Escrita y dirigida por John Francis Daley y Jonathan M. Goldstein.",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/A6jWpnsmiFJR9idlCOUCeP3m03I.jpg",
},
{
    "id": 2,
    "name": "BAYWATCH",
    "nombre": "BAYWATCH",
    "genero": "ESTRENO 16 JUNIO",
    "clase": "2",
    "sipnosis": "COMEDIA",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/aPifsnK3ui76Cq7xMDe1AVlrA0k.jpg",
},
{
    "id": 3,
    "name": "Rapido-y-Furiosos",
    "nombre": "RAPIDO Y FURIOSOS",
    "genero": "Fast and furios",
    "clase": "3",
    "sipnosis": "ACCION",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/aIyqWTuf6NouKphVlxzbv9pblxQ.jpg",
},
{
    "id": 4,
    "name": "RABBIT",
    "nombre": "RABBIT",
    "genero": "Marvel Comics",
    "clase": "4",
    "sipnosis": "Niños",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/7qb6u23jMucfMlJ4MCSFo8djka1.jpg",
},
{
    "id": 5,
    "name": "EL CHAPO",
    "nombre": "EL CHAPO",
    "genero": "suspenso",
    "clase": "5",
    "sipnosis": "NARCOTRAFICO",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/khAED7ox0Dfk4Ef5LAf6jPEe4oy.jpg",
},
{
    "id": 6,
    "name": "CRUELLA",
    "nombre": "CRUELLA",
    "genero": "niños",
    "clase": "6",
    "sipnosis": "Infantil",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/5bsApWAUqb0jeXtHPjKQ6MZOtZJ.jpg",
},
{
    "id": 7,
    "name": "loki",
    "nombre": "LOKI",
    "genero": "Accion",
    "clase": "7",
    "sipnosis": "La nueva serie Loki, de Marvel Studios, empieza allí donde terminó Vengadores: Endgame. En ella, el voluble villano Loki vuelve a ganarse el apodo de Dios del Engaño",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/kAHPDqUUciuObEoCgYtHttt6L2Q.jpg",
},
{
    "id": 8,
    "name": "lareina del flow",
    "nombre": "LA REINA DEL FLOW",
    "genero": "Misterio Drama Crimen",
    "clase": "8",
    "sipnosis": "La serie se desarrolla en el seductor ambiente del reggaeton, género que se ha tomado al mundo. Esta es la historia de Yeimy Montoya, una talentosa joven compositora que paga una injusta condena en una prisión de Nueva York tras ser engañada por Charly, el hombre que ama y que posteriormente le roba sus canciones, con las que logra alcanzar la fama y convertirse en una estrella. El único deseo de Yeimy es salir a cobrar venganza contra todos aquellos que acabaron con su vida y su familia.",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/fuVuDYrs8sxvEolnYr0wCSvtyTi.jpg",
},
{
    "id": 9,
    "name": "elite",
    "nombre": "ELITE",
    "genero": "crimen misterio drama",
    "clase": "9",
    "sipnosis": "Las Encinas, un exclusivo colegio privado al que la élite social del país envía a sus hijos. Pero en el centro son admitidos tres adolescentes de familias humildes después de que un terremoto destruyera el colegio público en el que estudiaban. El choque de clases genera diversos problemas que se agravan hasta que, de repente, se produce un asesinato.",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/g4iITTkAd0l1bVRk5gDSU6wfue6.jpg",
},
{
    "id": 10,
    "name": "VIKINGOS",
    "nombre": "The Walking Dead ",
    "genero": "vikingos",
    "clase": "10",
    "sipnosis": "Está ambientada en un futuro apocalíptico con la Tierra devastada por el efecto de un cataclismo, que ha provocado la mutación en zombies de la mayor parte de los habitantes del planeta. La serie, explora las dificultades de los protagonistas para sobrevivir en un mundo poblado por el horror, así como las relaciones personales que se establecen entre ellos, en ocasiones también una amenaza para su supervivencia.",
    "image": "https://www.themoviedb.org/t/p/w220_and_h330_face/AbgAKXMmTU509Q1uws1IC3IluSd.jpg",
}]